name: Test - e2e

on:
  workflow_dispatch:

jobs:
  test-win:
    runs-on: windows-latest
    timeout-minutes: 30

    steps:
      - name: Download latest release
        run: |
          iwr https://github.com/jmoalves/levain/releases/latest/download/install.ps1 | iex
          call levain
