name: Test - e2e

on:
  workflow_dispatch:
    inputs:
      levainVersion:
        description: 'Levain version (optional - Default=latest)'
        required: false

jobs:
  e2e-win:
    runs-on: windows-latest
    timeout-minutes: 30

    steps:
      - name: Install Levain
        run: |
          # Which levain version?
          $levainVersion = "${{ github.event.inputs.levainVersion }}"

          # Install script
          $scriptUrl = if ($levainVersion) {
            $scriptUrl = "https://github.com/jmoalves/levain/releases/download/v${levainVersion}/install.ps1"
          } else {
            $scriptUrl = "https://github.com/jmoalves/levain/releases/latest/download/install.ps1"
          }

          ###
          # Workaround until install maturity
          $scriptUrl = "https://raw.githubusercontent.com/jmoalves/levain/master/install/install.ps1"
          ###

          # Headless
          $levainHeadless = "true"

          # Install
          iwr $scriptUrl | iex
          
          # Workaround - ADD Levain to GitHub PATH
          Add-Content $env:GITHUB_PATH "$HOME\levain\levain"

      - name: Levian list
        shell: cmd
        run: |
          levain list

      - name: Levian install
        shell: cmd
        run: |
          levain install wlp-runtime-24.0.0.1 jdk-8-ibm jdk-11-ibm jdk-17-ibm jdk-21-ibm git maven-3.9 deno umlet

      - name: Levian context-menu
        shell: cmd
        run: |
          levain install levain-context-menu

      - name: Levian update
        shell: cmd
        run: |
          levain update
  