name: Test - e2e

on:
  workflow_dispatch:
    inputs:
      levainVersion:
        description: 'Levain version (optional - Default=latest)'
        required: false

jobs:
  e2e-win:
    runs-on: windows-latest
    timeout-minutes: 30

    steps:
      - name: Install Levain
        run: |
          # Which levain version?
          $v = "${{ github.event.inputs.levainVersion }}"

          # Install script
          $scriptUrl = "https://raw.githubusercontent.com/jmoalves/levain/master/install/install.ps1"
          # $scriptUrl = "https://github.com/jmoalves/levain/releases/latest/download/install.ps1"

          # Install
          iwr $scriptUrl | iex
          
          # Workaround - ADD Levain to GitHub PATH
          Add-Content $env:GITHUB_PATH "$HOME\levain\levain"

      - name: Levian list
        shell: cmd
        run: |
          levain list

      - name: Levian install
        shell: cmd
        run: |
          levain install wlp-runtime-22.0.0.6 jdk-17-ibm git maven-3.8 deno umlet

      - name: Levian update
        shell: cmd
        run: |
          levain update
  