name: Test - e2e

on:
  workflow_dispatch:
    inputs:
      levainVersion:
        description: 'Levain version (optional - Default=latest)'
        required: false

  release:
    types: [published]        

  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 6 * * SUN'
      
jobs:
  e2e-win:
    runs-on: windows-latest
    timeout-minutes: 30

    steps:
      - name: Echo
        shell: cmd
        run: echo REF=%GITHUB_REF%

      - name: Install Levain
        run: |
          # Which levain version?
          $levainVersion = "${{ github.event.inputs.levainVersion }}"

          # Install script
          $scriptUrl = if ($levainVersion) {
            $scriptUrl = "https://github.com/jmoalves/levain/releases/download/v${levainVersion}/install.ps1"
          } else {
            $scriptUrl = "https://github.com/jmoalves/levain/releases/latest/download/install.ps1"
          }

          ###
          # Workaround until install maturity
          $scriptUrl = "https://raw.githubusercontent.com/jmoalves/levain/master/install/install.ps1"
          ###

          # Headless
          $levainHeadless = "true"

          # Install
          iwr $scriptUrl | iex
          
          # Workaround - ADD Levain to GitHub PATH
          Add-Content $env:GITHUB_PATH "$HOME\levain\levain"

      - name: Levian list
        shell: cmd
        run: |
          levain list

      - name: Run Microsoft Security DevOps
        uses: microsoft/security-devops-action@v1
        id: msdo-levain
  
      - name: Levian install EVERYTHING
        shell: cmd
        run: |
          @echo off

          SETLOCAL EnableDelayedExpansion
          
          set pkgList=
          for /f "usebackq tokens=*" %%a in (`powershell "levain list | Select-String -Pattern '^   [a-zA-Z0-9]' | foreach{ $_.ToString().Trim() }"`) do (
            echo "=%%a="
            set pkgList=!pkgList!%%a 
          )
          
          call levain install %pkgList%
          set pkgList=

      - name: Run Microsoft Security DevOps
        uses: microsoft/security-devops-action@v1
        id: msdo-install

      - name: Levian update
        shell: cmd
        run: |
          levain update

      - name: Run Microsoft Security DevOps
        uses: microsoft/security-devops-action@v1
        id: msdo-update
  