name: Test - e2e

on:
  workflow_dispatch:

jobs:
  e2e-win:
    runs-on: windows-latest
    timeout-minutes: 30

    steps:
      - name: Install Levain
        run: |
          # Which levain version?
          # $v="0.80.7"

          # Install script
          $scriptUrl = "https://raw.githubusercontent.com/jmoalves/levain/master/install/install.ps1"
          # $scriptUrl = "https://github.com/jmoalves/levain/releases/latest/download/install.ps1"

          # Install
          iwr $scriptUrl | iex
          $v=[Environment]::GetEnvironmentVariable("PATH", "User"); Write-Output "UserPath = $v"

      - name: Run Levain
        shell: cmd
        run: |
          path
          call levain
