name: Test - e2e

on:
  workflow_dispatch:

jobs:
  test-win:
    runs-on: windows-latest
    timeout-minutes: 30

    steps:
      - name: Download latest release
        run: |
          # Which levain version?
          # $v="0.80.7"

          # Install script
          $scriptUrl = https://raw.githubusercontent.com/jmoalves/levain/master/install/install.ps1
          # $scriptUrl = https://github.com/jmoalves/levain/releases/latest/download/install.ps1

          # Install
          iwr $scriptUrl | iex

      - name: Run levain
        shell: cmd
        run: |
          call levain
